<?php

class BrevoCURLMail
{
	public $result, $keys, $CI, $pool, $headers;

	public function __construct()
	{
		$this->pool = array();
		$this->headers = array();
		$this->keys = array();

		$this->CI = &get_instance();
		$this->result = $this->CI->db->select(['config_key', 'value'])->get('app_config')->result_array();

		$this->CI->encryption->initialize(
			array(
				'cipher' => 'aes-256',
				'mode' => 'ctr',
			)
		);

		foreach ($this->result as $key => $row) {
			$this->keys[$row['config_key']] = $this->CI->encryption->decrypt($row['value']);
		}

	}

	public function _init_($sandboxMode = true)
	{
		$this->headers[] = 'Accept: application/json';
		$this->headers[] = 'Api-Key: ' . $this->keys['brevo_api_key'];
		$this->headers[] = 'Content-Type: application/json';

		if ($sandboxMode) {
			// $this->pool['headers'] =  [
			// 	"X-Sib-Sandbox" =>  "drop"
			// ];
		}
		return $this;
	}
	public function config_plaintext($sender, $to, $subject, $body)
	{
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$this->pool["sender"] = $sender ?? [
			"name" =>  "LOT Awards",
			"email" =>  "noreply@leadersoftomorrow.co.in"
		];

		$this->pool["to"] = $to ?? [
			[
				"email" =>  "hemant@sociomark.in",
				"name" =>  "Hemant Karekar"
			]
		];
		// $this->pool["htmlContent"] = "<!DOCTYPE html> <html> <body> <h1>Confirm you email</h1> <p>Please confirm your email address by clicking on the link below</p> </body> </html>",
		$this->pool["textContent"] = $body ?? "Please confirm your email address by clicking on the link https://text.domain.com";
		$this->pool["subject"] = $subject ?? "Login Email confirmation";

		return $this;
	}

	public function send()
	{
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://api.brevo.com/v3/smtp/email');
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($this->pool));

		curl_setopt($ch, CURLOPT_HTTPHEADER, $this->headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		} else {
			return true;
		}
		curl_close($ch);
	}
}
